auto_exposure: true
auto_frame_rate: true
auto_gain: true
auto_packet_size: false
auto_shutter: true
auto_white_balance: false
brightness: 0.0
enable_strobe1: false
enable_trigger: false
enable_trigger_delay: false
exposure: 1.35

format7_color_coding: raw
format7_roi_height: 0
format7_roi_width: 0
format7_x_offset: 0
format7_y_offset: 0

frame_id: 'camera'

# When unspecified, the driver will use the default framerate as given by the
# camera itself. Use this parameter to override that value for cameras capable of
# other framerates.
frame_rate: 13

gain: 0.0
gamma: 1.0
packet_delay: 400
packet_size: 1400
pan: 0
serial: 0
shutter_speed: 0.03
strobe1_delay: 0.0
strobe1_duration: 1.0
strobe1_polarity: 0
tilt: 0
trigger_delay: 0.0
trigger_mode: mode0
trigger_parameter: 0
trigger_polarity: 0
trigger_source: gpio0
video_mode: format7_mode0
white_balance_blue: 800
white_balance_red: 550

# Use the camera_calibration package to create this file
#camera_info_url: '~/.ros/camera_info/$(arg camera_serial).yaml'
